--- 
title: "rOpenSci Blog Guide for Authors and Editors"
author: "Stefanie Butland, Steffi LaZerte, Maëlle Salmon, Yanina Bellini Saibene"
date: "`r Sys.Date()`"
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: ropensci-org/blog-guidance
twitter: ropensci
url: 'https\://blogguide.ropensci.org/'
description: "Blog post guidance"
apple-touch-icon: "favicon/apple-touch-icon.png"
apple-touch-icon-size: 120
favicon: "favicon/favicon.ico"
---

# Preface {-}

The purpose of this documentation is to provide a guide for authors and editors of blog posts and tech notes for the rOpenSci website.
We created it after reviewing and publishing over 100 posts by community members, in hopes of addressing many frequently asked questions, and frequently given suggestions. 

The volume of information may be overwhelming at first. 
Some of the guidance indicates things we require that you do (such as creating an author file with your metadata), while most of the guidance is information to help you (such as how to add an image to your post).

**What's in the book and what's required reading?**

- Chapter 1 [Content Guidelines](#content) coaches you in thinking through what you might say in your post.

- Chapter 2 [Technical Guidelines](#technical) is **required reading** for submitting a post - from drafting in an (R) Markdown template to submitting for review using GitHub pull request infrastructure. 

- Chapter 3 [Responding to Editor’s Review](#respond) is **required reading**, briefly outlining how to find and respond to an editor's comments in the GitHub pull request review interface.

- Chapter 4 [Publication and Promotion](#promote) provides some motivation for doing the extra work to contribute a post by outlining what rOpenSci does to promote it.

- Chapters 5 and 6 provide [guidelines for editors](#editor) reviewing, publishing and promoting posts and outine editorial [governance](#editormeta).


If you find any errors or things that need clarification, we would be grateful if you opened an issue or pull request in the [repository for this book](https://github.com/ropensci-org/blog-guidance).

_We are thankful for the feedback and contributions from [Hugo Gruson](https://github.com/Bisaloo), [Mark Padgham](https://github.com/mpadge), and [Diego Hernangómez](https://github.com/dieghernan)._

